# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - release
cache: packages
warnings_are_errors: true
os:
  - linux
  - osx
apt_packages:
  - libharfbuzz-dev
  - libfribidi-dev
after_success:
  - Rscript -e 'covr::coveralls()'
  - Rscript -e 'pkgdown::build_site()'
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master
    os: linux
